# Generated by Django 4.2.17 on 2024-12-22 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publish_date',
            new_name='published_date',
        ),
    ]
