# Generated by Django 4.2.17 on 2024-12-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_publish_date_book_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Business Analytics', 'Business Analytics'), ('Python', 'Python'), ('Data Science', 'Data Science'), ('Math', 'Math')], default='Math', max_length=255),
        ),
    ]
